<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Product $item */
/** @var ProductCompare $compareViewModel */
/** @var HeroiconsOutline $heroicons */
/** @var Wishlist $wishlistViewModel */
/** @var ProductPage $productViewModel */
/** @var ProductListItem $productListItemViewModel */

$heroicons = $viewModels->require(HeroiconsOutline::class);
$compareViewModel = $viewModels->require(ProductCompare::class);
$wishlistViewModel = $viewModels->require(Wishlist::class);
$productViewModel = $viewModels->require(ProductPage::class);
$productListItemViewModel = $viewModels->require(ProductListItem::class);

$item = $block->getData('item');
$image = $productViewModel->getImage($item, 'category_page_grid');
?>
<a href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>"
   class="relative flex items-center bg-white product photo product-item-photo"
   style="padding-top:100%"
   tabindex="-1">
        <span class="absolute top-0 left-0 flex flex-wrap content-center w-full h-full p-2
            overflow-hidden align-center hover:shadow-sm">
            <img class="self-center w-full h-auto"
                 src="<?= $escaper->escapeHtmlAttr($image->getImageUrl()) ?>"
                 alt="<?= $escaper->escapeHtmlAttr($image->getLabel()) ?>"
                 loading="lazy"
                 width="<?= $escaper->escapeHtmlAttr($image->getWidth()) ?>"
                 height="<?= $escaper->escapeHtmlAttr($image->getHeight()) ?>"
            />
        </span>
</a>

<p class="flex items-center justify-center px-1 pt-3 text-primary">
    <a class="truncate product-item-link" href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>">
        <span><?= /** @noEscape */ $productViewModel->productAttributeHtml($item, $item->getName(), 'name') ?></span>
    </a>
</p>
<p class="pt-1 text-lg text-center text-gray-900">
    <?= /** @noEscape */ $productViewModel->currency($item->getFinalPrice()) ?>
</p>
<p class="flex flex-wrap gap-2 inline px-1 pt-3">
    <a class="justify-center w-auto mr-auto btn btn-primary"
       href="<?= $escaper->escapeUrl($item->getProductUrl()) ?>">
        <span class="inline"><?= $escaper->escapeHtml(__('View Product')) ?></span>
    </a>
    <span class="inline-flex gap-2 ml-auto">
        <?php if ($compareViewModel->showInProductList()): ?>
            <button type="button"
                    @click="$dispatch('product-add-to-compare', {productId: <?= (int) $item->getId() ?>})"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                    class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex
                           items-center justify-center text-gray-500 hover:text-yellow-500"
            >
            <?= $heroicons->scaleHtml("w-5 h-5") ?>
        </button>
        <?php endif; ?>
        <?php if ($wishlistViewModel->isEnabled()): ?>
            <button type="button"
                    @click="$dispatch('product-add-to-wishlist', {productId: <?= (int) $item->getId() ?>})"
                    aria-label="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>"
                    class="inline-flex items-center justify-center w-10 h-10 p-0 ml-auto
                           text-gray-500 bg-gray-200 border-0 rounded-full hover:text-red-600"
            >
                <?= $heroicons->heartHtml("w-5 h-5", 25, 25) ?>
            </button>
        <?php endif; ?>
    </span>
</p>
