<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer
 * @var \Magento\Framework\Escaper $escaper
 */
$item = $block->getItem();
?>
<div class="lg:grid lg:grid-cols-5 py-2">
    <div class="p-2 col-span-2">
        <span class="grid-cols-2 font-semibold"><?= $escaper->escapeHtml($item->getName()) ?></span>
        <div class="item-options col-span-2 lg:col-span-1 mt-2">
            <div class="text-sm flex">
                <span><?= $escaper->escapeHtml(__('Sku')) ?>:</span>
                <span class="text-sm ml-1"><?= /* @noEscape */
                    $block->prepareSku($block->getSku()) ?></span>
            </div>
            <?php if ($_options = $block->getItemOptions()) : ?>
                <?php foreach ($_options as $_option) : ?>
                    <div class="text-sm flex mt-1">
                        <span><?= $escaper->escapeHtml($_option['label']) ?>:</span>
                        <?php if (!$block->getPrintStatus()) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <span class="ml-1">
                                <?= $escaper->escapeHtml($_formatedOptionValue['value'], ['a', 'img']) ?>
                        </span>
                        <?php else : ?>
                            <span class="ml-1"><?= $escaper->escapeHtml(
                                    (isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])
                                ) ?>
                            </span>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addtInfoBlock) : ?>
                <?= $addtInfoBlock->setItem($item)->toHtml() ?>
            <?php endif; ?>
            <?= $escaper->escapeHtml($item->getDescription()) ?>
        </div>
    </div>
    <div class="p-2 flex justify-between lg:block">
        <p class="lg:hidden font-medium"><?= $escaper->escapeHtml(__('Price')) ?></p>
        <?= $block->getItemPriceHtml() ?>
    </div>
    <div class="p-2 flex justify-between lg:block">
        <p class="lg:hidden font-medium"><?= $escaper->escapeHtml(__('Qty')) ?></p>
        <div class="text-right lg:text-left">
            <?php if ($block->getItem()->getQtyOrdered() > 0) : ?>
                <p>
                    <span class="title"><?= $escaper->escapeHtml(__('Ordered')) ?>:</span>
                    <span class="content"><?= (float)$block->getItem()->getQtyOrdered() ?></span>
                </p>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyShipped() > 0) : ?>
                <p>
                    <span class="title"><?= $escaper->escapeHtml(__('Shipped')) ?>:</span>
                    <span class="content"><?= (float)$block->getItem()->getQtyShipped() ?></span>
                </p>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyCanceled() > 0) : ?>
                <p>
                    <span class="title"><?= $escaper->escapeHtml(__('Canceled')) ?>:</span>
                    <span class="content"><?= (float)$block->getItem()->getQtyCanceled() ?></span>
                </p>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyRefunded() > 0) : ?>
                <p>
                    <span class="title"><?= $escaper->escapeHtml(__('Refunded')) ?>:</span>
                    <span class="content"><?= (float)$block->getItem()->getQtyRefunded() ?></span>
                </p>
            <?php endif; ?>
        </div>
    </div>
    <div class="p-2 text-right flex justify-between lg:block">
        <p class="lg:hidden font-medium"><?= $escaper->escapeHtml(__('Subtotal')) ?></p>
        <?= $block->getItemRowTotalHtml() ?>
    </div>
</div>
