<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Product\Placeholder;
use Magento\Catalog\Block\Product\View\Gallery;
use Magento\Framework\Escaper;

/** @var Gallery $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Placeholder $placeholder */
$placeholder = $viewModels->require(Placeholder::class);

$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, [$block, 'isMainImage']));

if (!empty($images) && empty($mainImage)) {
    $mainImage = reset($images);
}

$mainImageSrc = $mainImage
    ? $mainImage->getData('medium_image_url')
    : $placeholder->getPlaceholderUrl('image');
?>

<link rel="preload" href="<?= $escaper->escapeUrl($mainImageSrc) ?>" as="image">
