<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Customer\Block\Widget\Name;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\ReCaptcha;

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaper */

/** @var ReCaptcha $recaptchaViewModel */
//Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency on
//Magento's Recaptcha module
$recaptchaViewModel = $block->getData('viewModelRecaptcha');
$recaptchaScriptTokenBlock = '';
$formId = $block->getFormId();
if ($recaptchaViewModel !== null && $formId && $recaptchaData = $recaptchaViewModel->getRecaptchaData($formId)) {
    $recaptchaScriptTokenBlock = $recaptchaData[ReCaptcha::RECAPTCHA_SCRIPT_TOKEN];
}
?>

<?= $block->getBlockHtml($recaptchaScriptTokenBlock) ?>

